controller_list:
  - name: fake_fanuc_m20ia_controller
    type: $(arg execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
initial:  # Define initial robot poses.
  - group: fanuc_m20ia
    pose: home